# Плагина разработан студией ManyDev
# ТГК: https://t.me/many_dev
# ВК: https://vk.com/many_dev

messages:
  start-regeneration: "&#C3FBE2» &#FFFFFFРегенерация шалкеров была запущена"
  stop-regeneration: "&#C3FBE2» &#FFFFFFРегенерация шалкеров была остановлена"
  reload: "&#C3FBE2» &#FFFFFFПлагин был перезагружен"
  break: "&#C3FBE2» &#FFFFFFШалкер осталось сломать %amount% раз!"
  no-permission: "&#C3FBE2» &#FFFFFFНет прав на выполнение этой команды."
  no-command: "&#C3FBE2» &#FFFFFFТакой команды нет"

shulkers:
  explosion:
    enabled: true
    damage: 10.0
    radius-damage: 10.0
  time-regeneration: 50 # раз во сколько секунд спавнятся шалкера
  min: 1 # минимальное кол-во шалкеров при спавне
  max: 5 # максимальное кол-во шалкеров при спавне
  locations:
    # здесь локации, где они могут спавнится, локации выбераются на рандом, где они будут заспавнены
    1:
      world: "world"
      x: 120
      y: 84
      z: 37
    2:
      world: "world"
      x: 129
      y: 84
      z: 37
    3:
      world: "world"
      x: 132
      y: 84
      z: 48
    4:
      world: "world"
      x: 120
      y: 84
      z: 50
    5:
      world: "world"
      x: 122
      y: 84
      z: 23
  rarities: # редкости
    default:
      chance: 60 # шанс на то, что шалкер будет такой категории
      material: "GRAY_SHULKER_BOX"
      amount-breaks: 5 # сколько раз нужно сломать, чтобы выпал дроп и пропал шалкер
      loot: # настройка лута
        min: 5 # минимальное кол-во выпадающих предметов
        max: 12 # максимальное кол-во выпадающих предметов
        items: # настройка предметов
          1:
            chance: 20
            material: "OBSIDIAN"
            # далее настройка разных параметров с возможностью использовать и не использовать их
            # amount:
            #  min: 1
            #  max: 1
            # name: ''
            # lore:
            #  - ''
            # pdt:
            #  - ''
            # enchantments:
            #  - 'LUCK:1'
            # itemflags:
            #  - 'HIDE_ENCHANTS'
          2:
            chance: 20
            material: "DIAMOND"
            amount:
              min: 5
              max: 30
          3:
            chance: 20
            material: "DIAMOND_SWORD"
            name: '&fManyDev бустит'
            lore:
              - ''
              - '&fТГК: https://t.me/many_dev'
              - '&fВК: https://vk.com/many_dev'
            enchantments:
              - 'DAMAGE_ALL:5'
            amount:
              min: 1
              max: 1
          4:
            chance: 20
            material: "EXPERIENCE_BOTTLE"
            amount:
              min: 5
              max: 50
          5:
            chance: 20
            material: "GOLD_INGOT"
            amount:
              min: 8
              max: 50
    rare:
      chance: 40 # шанс на то, что шалкер будет такой категории
      material: "RED_SHULKER_BOX"
      amount-breaks: 10 # сколько раз нужно сломать, чтобы выпал дроп и пропал шалкер
      loot: # настройка лута
        min: 3 # минимальное кол-во выпадающих предметов
        max: 22 # максимальное кол-во выпадающих предметов
        items: # настройка предметов
          1:
            chance: 25
            material: "NETHERITE_SCRAP"
            # далее настройка разных параметров с возможностью использовать и не использовать их
            amount:
              min: 1
              max: 5
            # name: ''
            # lore:
            #  - ''
            # pdt:
            #  - ''
            # enchantments:
            #  - 'LUCK:1'
            # itemflags:
            #  - 'HIDE_ENCHANTS'
          2:
            chance: 20
            material: "NETHERITE_AXE"
            amount:
              min: 1
              max: 1
          3:
            chance: 20
            material: "NETHERITE_SWORD"
            amount:
              min: 1
              max: 1
          4:
            chance: 20
            material: "NETHERITE_SWORD"
            name: '&fDreamCode бустит'
            lore:
              - ''
              - '&fТГК: https://t.me/dreamcode_studio'
              - '&fВК: https://vk.com/dmcode'
            enchantments:
              - 'DAMAGE_ALL:5'
            amount:
              min: 1
              max: 1
          5:
            chance: 20
            material: "GOLD_INGOT"
            amount:
              min: 3
              max: 20