messages:
  start-regeneration: "&2Регенерация шалкеров была запущена."
  stop-regeneration: "&2Регенерация шалкеров была остановлена"
  reload: "&2Плагин был перезагружен."
  break: "Тебе нужно сломать ещё %amount% раз!"
  no_permission: "&cНет прав на выполнение этой команды."
  no_command: "&cТакой команды нет."

shulkers:
  time-regeneration: 50 # раз во сколько секунд спавнятся шалкера
  min: 4 # минимальное кол-во шалкеров при спавне
  max: 5 # максимальное кол-во шалкеров при спавне
  locations:
    # здесь локации, где они могут спавнится, локации выбераются на рандом, где они будут заспавнены
    1:
      world: "world"
      x: 101
      y: 100
      z: 100
    2:
      world: "world"
      x: 102
      y: 100
      z: 100
    3:
      world: "world"
      x: 103
      y: 100
      z: 100
    4:
      world: "world"
      x: 104
      y: 100
      z: 100
    5:
      world: "world"
      x: 105
      y: 100
      z: 100
  rarities: # редкости
    default:
      chance: 50 # шанс на то, что шалкер будет такой категории
      material: "GRAY_SHULKER_BOX"
      amount-breaks: 5 # сколько раз нужно сломать, чтобы выпал дроп и пропал шалкер
      loot: # настройка лута
        min: 2 # минимальное кол-во выпадающих предметов
        max: 5 # максимальное кол-во выпадающих предметов

        items: # настройка предметов
          1:
            chance: 20
            material: "OBSIDIAN"
            # далее настройка разных параметров с возможностью использовать и не использовать их
            # amount:
            #  min: 1
            #  max: 1
            # name: ''
            # lore:
            #  - ''
            # pdt:
            #  - ''
            # enchantments:
            #  - 'LUCK:1'
            # itemflags:
            #  - 'HIDE_ENCHANTS'
          2:
            chance: 20
            material: "DIAMOND"
            amount:
              min: 1
              max: 1
          3:
            chance: 20
            material: "COBBLESTONE"
            amount:
              min: 1
              max: 1
          4:
            chance: 20
            material: "OAK_DOOR"
            amount:
              min: 1
              max: 1
          5:
            chance: 20
            material: "BIRCH_BUTTON"
            amount:
              min: 1
              max: 1
    legendary:
      chance: 20 # шанс на то, что шалкер будет такой категории
      material: "RED_SHULKER_BOX"
      amount-breaks: 10 # сколько раз нужно сломать, чтобы выпал дроп и пропал шалкер
      loot: # настройка лута
        min: 1 # минимальное кол-во выпадающих предметов
        max: 7 # максимальное кол-во выпадающих предметов

        items: # настройка предметов
          1:
            chance: 15
            material: "DIAMOND_SWORD"
            # далее настройка разных параметров с возможностью использовать и не использовать их
            # amount:
            #  min: 1
            #  max: 1
            # name: ''
            # lore:
            #  - ''
            # pdt:
            #  - ''
            # enchantments:
            #  - 'LUCK:1'
            # itemflags:
            #  - 'HIDE_ENCHANTS'
          2:
            chance: 30
            material: "NETHERITE_AXE"
            amount:
              min: 1
              max: 1
          3:
            chance: 20
            material: "NETHERITE_SWORD"
            amount:
              min: 1
              max: 1
          4:
            chance: 30
            material: "PURPLE_BED"
            amount:
              min: 5
              max: 15
          5:
            chance: 5
            material: "RED_BED"
            amount:
              min: 15
              max: 50