messages:
  start-regeneration: "&2Регенерация шалкеров была запущена."
  stop-regeneration: "&2Регенерация шалкеров была остановлена"
  reload: "&2Плагин был перезагружен."
  break: "Тебе нужно сломать ещё %amount% раз!"
  no_permission: "&cНет прав на выполнение этой команды."

shulkers:
  time-regeneration: 2 # раз во сколько секунд спавнятся шалкера
  min: 1 # минимальное кол-во шалкеров при спавне
  max: 5 # максимальное кол-во шалкеров при спавне
  locations:
    # здесь локации, где они могут спавнится, локации выбераются на рандом, где они будут заспавнены
    1:
      world: "world"
      x: 100
      y: 100
      z: 100
  rarities: # редкости
    default:
      chance: 60 # шанс на то, что шалкер будет такой категории
      material: "GRAY_SHULKER_BOX"
      amount-breaks: 5 # сколько раз нужно сломать, чтобы выпал дроп и пропал шалкер
      loot: # настройка лута
        min: 3 # минимальное кол-во выпадающих предметов
        max: 5 # максимальное кол-во выпадающих предметов

        items: # настройка предметов
          1:
            chance: 50
            material: "DIAMOND_SWORD"
            # далее настройка разных параметров с возможностью использовать и не использовать их
            # amount:
            #  min: 1
            #  max: 1
            # name: ''
            # lore:
            #  - ''
            # pdt:
            #  - ''
            # enchantments:
            #  - 'LUCK:1'
            # itemflags:
            #  - 'HIDE_ENCHANTS'
          2:
            chance: 30
            material: "DIAMOND"
            amount:
              min: 5
              max: 8
          3:
            chance: 20
            material: "ENCHANTED_GOLDEN_APPLE"
            amount:
              min: 1
              max: 1
    epic:
      chance: 40 # шанс на то, что шалкер будет такой категории
      material: "BLUE_SHULKER_BOX"
      amount-breaks: 10 # сколько раз нужно сломать, чтобы выпал дроп и пропал шалкер
      loot: # настройка лута
        min: 5 # минимальное кол-во выпадающих предметов
        max: 7 # максимальное кол-во выпадающих предметов

        items: # настройка предметов
          1:
            chance: 15
            material: "DIAMOND_SWORD"
            # далее настройка разных параметров с возможностью использовать и не использовать их
            # amount:
            #  min: 1
            #  max: 1
            # name: ''
            # lore:
            #  - ''
            # pdt:
            #  - ''
            # enchantments:
            #  - 'LUCK:1'
            # itemflags:
            #  - 'HIDE_ENCHANTS'
          2:
            chance: 30
            material: "DIAMOND"
            amount:
              min: 5
              max: 8
          3:
            chance: 20
            material: "ENCHANTED_GOLDEN_APPLE"
            amount:
              min: 1
              max: 1
          4:
            chance: 30
            material: "GOLD_INGOT"
            amount:
              min: 5
              max: 15
          5:
            chance: 5
            material: "EXPERIENCE_BOTTLE"
            amount:
              min: 15
              max: 50